version: "3.9"
services: 
  frontend: 
    build: app
    ports:
      - "8080:8080"
  api:
    build: server
    ports:
      - "8000:8000"
    expose:
      - "3306"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: eric
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
